import {
	TEXT_BUTTON_ADD_WISH,
	TEXT_BUTTON_DELETE_WISH,
	TEXT_BUTTON_GRANT_WISH,
	TEXT_BUTTON_UNREALIZED_WISHES,
	TEXT_BUTTON_GRANTED_WISHES,
	TEXT_BUTTON_PREV,
	TEXT_BUTTON_NEXT,
	TEXT_BUTTON_SHARE_WISH,
	TEXT_BUTTON_MENU,
	TEXT_BUTTON_BACK_TO_LIST,
	TEXT_BUTTON_ADD_LINK,
	TEXT_BUTTON_EDIT_WISH,
	TEXT_BUTTON_EDIT_TITLE,
	TEXT_BUTTON_EDIT_LINK,
	TEXT_BUTTON_BACK,
	TEXT_BUTTON_SHARE_PAGE_LIST,
	TEXT_BUTTON_SHARE_ALL_LIST,
} from "./constants.js";

export const mainKeyboard = {
	addWish: TEXT_BUTTON_ADD_WISH,
	unrealizedWishes: TEXT_BUTTON_UNREALIZED_WISHES,
	grantedWishes: TEXT_BUTTON_GRANTED_WISHES,
};
export const itemKeyboard = {
	deleteWish: TEXT_BUTTON_DELETE_WISH,
	grantWish: TEXT_BUTTON_GRANT_WISH,
	shareWish: TEXT_BUTTON_SHARE_WISH,
	editWish: TEXT_BUTTON_EDIT_WISH,
	backToMenu: TEXT_BUTTON_MENU,
	backToList: TEXT_BUTTON_BACK_TO_LIST,
};
export const listKeyboard = {
	prevPage: TEXT_BUTTON_PREV,
	nextPage: TEXT_BUTTON_NEXT,
	sharePageList: TEXT_BUTTON_SHARE_PAGE_LIST,
	shareAllList: TEXT_BUTTON_SHARE_ALL_LIST,
	backToMenu: TEXT_BUTTON_MENU,
};

export const addInfoKeyboard = {
	addLink: TEXT_BUTTON_ADD_LINK,
	backToMenu: TEXT_BUTTON_MENU,
};

export const editWishKeyboard = {
	editTitle: TEXT_BUTTON_EDIT_TITLE,
	editLink: TEXT_BUTTON_EDIT_LINK,
	back: TEXT_BUTTON_BACK,
};

export const backToMenu = {
	backToMenu: TEXT_BUTTON_MENU,
};
